# Working with API

In [26]:
# API
import pandas as pd
import requests

In [27]:
url = "https://covid-193.p.rapidapi.com/countries"
headers = {
    'x-rapidapi-host': 'covid-193.p.rapidapi.com',                              # identifies which API you are calling
	'x-rapidapi-key': '3d72a3ed40mshf6f339ded999111p1a51e5jsn1003e2db0078'      # authenticates your access (your API key)
}

a = requests.get(url, headers = headers)        # headers=headers means you are passing a variable named headers as the value for the headers parameter in the requests.get() function.
data = a.json()

data

{'get': 'countries',
 'parameters': [],
 'errors': [],
 'results': 231,
 'response': ['Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua-and-Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia-and-Herzegovina',
  'Botswana',
  'Brazil',
  'British-Virgin-Islands',
  'Brunei',
  'Bulgaria',
  'Burkina-Faso',
  'Burundi',
  'Cabo-Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'CAR',
  'Caribbean-Netherlands',
  'Cayman-Islands',
  'Chad',
  'Channel-Islands',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook-Islands',
  'Costa-Rica',
  'Croatia',
  'Cuba',
  'Cura&ccedil;ao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Diamond-Princess',
  'Djibouti',
  'Dominica',
  'Dominican-Republic',
  'DPRK',
  'DRC',
  'Ecuador',
  'Egypt',
  'El-Salvador',
  'Equatorial-Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Faeroe-Islands',
  'Falkland-Islands',
  'Fiji',
  'Finland',
  'France',
  'French-Guiana',
  'French-Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong-Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle-of-Man',
  'Israel',
  'Italy',
  'Ivory-Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall-Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'MS-Zaandam',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New-Caledonia',
  'New-Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'North-Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua-New-Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'R&eacute;union',
  'Romania',
  'Russia',
  'Rwanda',
  'S-Korea',
  'Saint-Helena',
  'Saint-Kitts-and-Nevis',
  'Saint-Lucia',
  'Saint-Martin',
  'Saint-Pierre-Miquelon',
  'Samoa',
  'San-Marino',
  'Sao-Tome-and-Principe',
  'Saudi-Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra-Leone',
  'Singapore',
  'Sint-Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon-Islands',
  'Somalia',
  'South-Africa',
  'South-Sudan',
  'Spain',
  'Sri-Lanka',
  'St-Barth',
  'St-Vincent-Grenadines',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad-and-Tobago',
  'Tunisia',
  'Turkey',
  'Turks-and-Caicos',
  'Tuvalu',
  'UAE',
  'Uganda',
  'UK',
  'Ukraine',
  'Uruguay',
  'USA',
  'Uzbekistan',
  'Vanuatu',
  'Vatican-City',
  'Venezuela',
  'Vietnam',
  'Wallis-and-Futuna',
  'Western-Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe']}

In [28]:
# read the html above and you will find that all the countries names are in 'response' column

data['response']        # printing a specific column of the data

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua-and-Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia-and-Herzegovina',
 'Botswana',
 'Brazil',
 'British-Virgin-Islands',
 'Brunei',
 'Bulgaria',
 'Burkina-Faso',
 'Burundi',
 'Cabo-Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'CAR',
 'Caribbean-Netherlands',
 'Cayman-Islands',
 'Chad',
 'Channel-Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook-Islands',
 'Costa-Rica',
 'Croatia',
 'Cuba',
 'Cura&ccedil;ao',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Diamond-Princess',
 'Djibouti',
 'Dominica',
 'Dominican-Republic',
 'DPRK',
 'DRC',
 'Ecuador',
 'Egypt',
 'El-Salvador',
 'Equatorial-Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faeroe-Islands',
 'Falkland-Islands',
 'Fiji',
 'Finland',
 'France',
 'French-Guiana',
 'French-Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong-Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle-of-Man',
 'Israel',
 'Italy',
 'Ivory-Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall-Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'MS-Zaandam',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New-Caledonia',
 'New-Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North-Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua-New-Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'R&eacute;union',
 'Romania',
 'Russia',
 'Rwanda',
 'S-Korea',
 'Saint-Helena',
 'Saint-Kitts-and-Nevis',
 'Saint-Lucia',
 'Saint-Martin',
 'Saint-Pierre-Miquelon',
 'Samoa',
 'San-Marino',
 'Sao-Tome-and-Principe',
 'Saudi-Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra-Leone',
 'Singapore',
 'Sint-Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon-Islands',
 'Somalia',
 'South-Africa',
 'South-Sudan',
 'Spain',
 'Sri-Lanka',
 'St-Barth',
 'St-Vincent-Grenadines',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad-and-Tobago',
 'Tunisia',
 'Turkey',
 'Turks-and-Caicos',
 'Tuvalu',
 'UAE',
 'Uganda',
 'UK',
 'Ukraine',
 'Uruguay',
 'USA',
 'Uzbekistan',
 'Vanuatu',
 'Vatican-City',
 'Venezuela',
 'Vietnam',
 'Wallis-and-Futuna',
 'Western-Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [29]:

pd.DataFrame(data['response'])         # converting api data into pandas data frame

                     0
0          Afghanistan
1              Albania
2              Algeria
3              Andorra
4               Angola
..                 ...
226  Wallis-and-Futuna
227     Western-Sahara
228              Yemen
229             Zambia
230           Zimbabwe

[231 rows x 1 columns]

In [30]:
url2 = "https://tourism-and-economic-impact.p.rapidapi.com/list"

payload = {}
headers2 = {
	"x-rapidapi-key": "3d72a3ed40mshf6f339ded999111p1a51e5jsn1003e2db0078",
	"x-rapidapi-host": "tourism-and-economic-impact.p.rapidapi.com",
	"Content-Type": "application/x-www-form-urlencoded"
}

response = requests.post(url2, data=payload, headers=headers2)


economy = response.json()
economy
# below we will be writing a code to convert this api key request into a pandas dataframe project

{'result': {'current_page': 1,
  'data': [{'country': 'Aruba',
    'country_code': 'ABW',
    'year': 1999,
    'tourism_receipts': 782000000,
    'tourism_arrivals': 972000,
    'tourism_exports': 62.5429,
    'tourism_departures': '',
    'tourism_expenditures': 9.49539,
    'gdp': 1722910000,
    'inflation': 2.28037,
    'unemployment': ''},
   {'country': 'Africa Eastern and Southern',
    'country_code': 'AFE',
    'year': 1999,
    'tourism_receipts': 8034210000,
    'tourism_arrivals': 15309400,
    'tourism_exports': 12.204,
    'tourism_departures': '',
    'tourism_expenditures': 7.76054,
    'gdp': 265429000000,
    'inflation': 7.81986,
    'unemployment': ''},
   {'country': 'Afghanistan',
    'country_code': 'AFG',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': None,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': None,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Africa Western and Central',
    'country_code': 'AFW',
    'year': 1999,
    'tourism_receipts': 1443610000,
    'tourism_arrivals': 3897980,
    'tourism_exports': 3.97448,
    'tourism_departures': '',
    'tourism_expenditures': 6.14729,
    'gdp': 139468000000,
    'inflation': 0.372266,
    'unemployment': ''},
   {'country': 'Angola',
    'country_code': 'AGO',
    'year': 1999,
    'tourism_receipts': 31000000,
    'tourism_arrivals': 45000,
    'tourism_exports': 0.583858,
    'tourism_departures': '',
    'tourism_expenditures': 2.48964,
    'gdp': 6152920000,
    'inflation': 248.196,
    'unemployment': ''},
   {'country': 'Albania',
    'country_code': 'ALB',
    'year': 1999,
    'tourism_receipts': 218000000,
    'tourism_arrivals': 371000,
    'tourism_exports': 55.9692,
    'tourism_departures': '',
    'tourism_expenditures': 3.69901,
    'gdp': 3212120000,
    'inflation': 0.389438,
    'unemployment': '18.4'},
   {'country': 'Andorra',
    'country_code': 'AND',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 9422000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 1240300000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Arab World',
    'country_code': 'ARB',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': None,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 665415000000,
    'inflation': 2.66937,
    'unemployment': ''},
   {'country': 'United Arab Emirates',
    'country_code': 'ARE',
    'year': 1999,
    'tourism_receipts': 893000000,
    'tourism_arrivals': None,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 84445500000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Argentina',
    'country_code': 'ARG',
    'year': 1999,
    'tourism_receipts': 3175000000,
    'tourism_arrivals': 2898000,
    'tourism_exports': 11.3404,
    'tourism_departures': '',
    'tourism_expenditures': 15.8891,
    'gdp': 283523000000,
    'inflation': None,
    'unemployment': '14.05'},
   {'country': 'Armenia',
    'country_code': 'ARM',
    'year': 1999,
    'tourism_receipts': 47000000,
    'tourism_arrivals': 41000,
    'tourism_exports': 12.1824,
    'tourism_departures': '',
    'tourism_expenditures': 5.64557,
    'gdp': 1845480000,
    'inflation': 0.648246,
    'unemployment': '11.2'},
   {'country': 'American Samoa',
    'country_code': 'ASM',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 41000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': None,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Antigua and Barbuda',
    'country_code': 'ATG',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 560000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 835515000,
    'inflation': 1.12129,
    'unemployment': ''},
   {'country': 'Australia',
    'country_code': 'AUS',
    'year': 1999,
    'tourism_receipts': 11408000000,
    'tourism_arrivals': 4459000,
    'tourism_exports': 15.2472,
    'tourism_departures': '3210000.0',
    'tourism_expenditures': 10.3625,
    'gdp': 389652000000,
    'inflation': 1.48313,
    'unemployment': '6.876'},
   {'country': 'Austria',
    'country_code': 'AUT',
    'year': 1999,
    'tourism_receipts': 12358000000,
    'tourism_arrivals': 17467000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 216422000000,
    'inflation': 0.568994,
    'unemployment': '4.699'},
   {'country': 'Azerbaijan',
    'country_code': 'AZE',
    'year': 1999,
    'tourism_receipts': 93000000,
    'tourism_arrivals': 602000,
    'tourism_exports': 7.25417,
    'tourism_departures': '1204000.0',
    'tourism_expenditures': 7.76645,
    'gdp': 4581250000,
    'inflation': -8.52517,
    'unemployment': '16.25'},
   {'country': 'Burundi',
    'country_code': 'BDI',
    'year': 1999,
    'tourism_receipts': 1200000,
    'tourism_arrivals': 26000,
    'tourism_exports': 2.01936,
    'tourism_departures': '27000.0',
    'tourism_expenditures': None,
    'gdp': 808077000,
    'inflation': 3.38542,
    'unemployment': '14.0'},
   {'country': 'Belgium',
    'country_code': 'BEL',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 6369000,
    'tourism_exports': None,
    'tourism_departures': '6410000.0',
    'tourism_expenditures': None,
    'gdp': 258246000000,
    'inflation': 1.12085,
    'unemployment': '8.649'},
   {'country': 'Benin',
    'country_code': 'BEN',
    'year': 1999,
    'tourism_receipts': 94400000,
    'tourism_arrivals': 941000,
    'tourism_exports': 15.7721,
    'tourism_departures': '',
    'tourism_expenditures': 7.40482,
    'gdp': 3677390000,
    'inflation': 0.326723,
    'unemployment': ''},
   {'country': 'Burkina Faso',
    'country_code': 'BFA',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 117000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 3389570000,
    'inflation': -1.07261,
    'unemployment': ''},
   {'country': 'Bangladesh',
    'country_code': 'BGD',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 173000,
    'tourism_exports': None,
    'tourism_departures': '1103000.0',
    'tourism_expenditures': 4.19828,
    'gdp': 51270600000,
    'inflation': 6.1067,
    'unemployment': ''},
   {'country': 'Bulgaria',
    'country_code': 'BGR',
    'year': 1999,
    'tourism_receipts': 1184000000,
    'tourism_arrivals': 5056000,
    'tourism_exports': 20.4322,
    'tourism_departures': '2376000.0',
    'tourism_expenditures': 11.3846,
    'gdp': 13627300000,
    'inflation': 2.57304,
    'unemployment': '14.1'},
   {'country': 'Bahrain',
    'country_code': 'BHR',
    'year': 1999,
    'tourism_receipts': 785000000,
    'tourism_arrivals': 3280000,
    'tourism_exports': 15.0334,
    'tourism_departures': '',
    'tourism_expenditures': 9.47528,
    'gdp': 7528470000,
    'inflation': -1.28759,
    'unemployment': ''},
   {'country': 'Bahamas, The',
    'country_code': 'BHS',
    'year': 1999,
    'tourism_receipts': 1598000000,
    'tourism_arrivals': 3648000,
    'tourism_exports': 72.3929,
    'tourism_departures': '',
    'tourism_expenditures': 11.8738,
    'gdp': 7683870000,
    'inflation': 1.25425,
    'unemployment': '7.45'},
   {'country': 'Bosnia and Herzegovina',
    'country_code': 'BIH',
    'year': 1999,
    'tourism_receipts': 258000000,
    'tourism_arrivals': 147000,
    'tourism_exports': 19.9156,
    'tourism_departures': '',
    'tourism_expenditures': 2.28851,
    'gdp': 4686260000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Belarus',
    'country_code': 'BLR',
    'year': 1999,
    'tourism_receipts': 92000000,
    'tourism_arrivals': None,
    'tourism_exports': 1.43757,
    'tourism_departures': '',
    'tourism_expenditures': 1.99844,
    'gdp': 12138200000,
    'inflation': 293.679,
    'unemployment': '2.1'},
   {'country': 'Belize',
    'country_code': 'BLZ',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 340000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': 8.29579,
    'gdp': 1000250000,
    'inflation': 2.6214,
    'unemployment': '12.84'},
   {'country': 'Bermuda',
    'country_code': 'BMU',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 549000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 3324430000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Bolivia',
    'country_code': 'BOL',
    'year': 1999,
    'tourism_receipts': 124000000,
    'tourism_arrivals': 342000,
    'tourism_exports': 9.46132,
    'tourism_departures': '253000.0',
    'tourism_expenditures': 5.88324,
    'gdp': 8285060000,
    'inflation': 2.15952,
    'unemployment': '3.93'},
   {'country': 'Brazil',
    'country_code': 'BRA',
    'year': 1999,
    'tourism_receipts': 1718000000,
    'tourism_arrivals': 5107000,
    'tourism_exports': 3.15258,
    'tourism_departures': '2863000.0',
    'tourism_expenditures': 5.50654,
    'gdp': 599642000000,
    'inflation': 4.85845,
    'unemployment': '11.125'},
   {'country': 'Barbados',
    'country_code': 'BRB',
    'year': 1999,
    'tourism_receipts': 734000000,
    'tourism_arrivals': 947000,
    'tourism_exports': 58.108,
    'tourism_departures': '',
    'tourism_expenditures': 9.75939,
    'gdp': 2951820000,
    'inflation': 1.56006,
    'unemployment': '10.61'},
   {'country': 'Brunei Darussalam',
    'country_code': 'BRN',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 967000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 6309070000,
    'inflation': -0.415628,
    'unemployment': ''},
   {'country': 'Bhutan',
    'country_code': 'BTN',
    'year': 1999,
    'tourism_receipts': 9000000,
    'tourism_arrivals': 7200,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 399311000,
    'inflation': 6.77699,
    'unemployment': '1.4'},
   {'country': 'Botswana',
    'country_code': 'BWA',
    'year': 1999,
    'tourism_receipts': 239000000,
    'tourism_arrivals': 1039000,
    'tourism_exports': 7.995,
    'tourism_departures': '',
    'tourism_expenditures': 6.48125,
    'gdp': 5484260000,
    'inflation': 7.7493,
    'unemployment': ''},
   {'country': 'Central African Republic',
    'country_code': 'CAF',
    'year': 1999,
    'tourism_receipts': 8000000,
    'tourism_arrivals': 10000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 999478000,
    'inflation': -1.4142,
    'unemployment': ''},
   {'country': 'Canada',
    'country_code': 'CAN',
    'year': 1999,
    'tourism_receipts': 12024000000,
    'tourism_arrivals': 49055000,
    'tourism_exports': 4.24503,
    'tourism_departures': '',
    'tourism_expenditures': 5.40185,
    'gdp': 678412000000,
    'inflation': 1.73484,
    'unemployment': '7.583'},
   {'country': 'Central Europe and the Baltics',
    'country_code': 'CEB',
    'year': 1999,
    'tourism_receipts': 20282600000,
    'tourism_arrivals': 200063000,
    'tourism_exports': 14.1329,
    'tourism_departures': '103358915.15008',
    'tourism_expenditures': 6.42737,
    'gdp': 435931000000,
    'inflation': 4.01914,
    'unemployment': '10.4170865946518'},
   {'country': 'Switzerland',
    'country_code': 'CHE',
    'year': 1999,
    'tourism_receipts': 9135000000,
    'tourism_arrivals': 7154000,
    'tourism_exports': 7.51514,
    'tourism_departures': '',
    'tourism_expenditures': 7.225,
    'gdp': 297874000000,
    'inflation': 0.806444,
    'unemployment': '3.053'},
   {'country': 'Channel Islands',
    'country_code': 'CHI',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': None,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 6262740000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Chile',
    'country_code': 'CHL',
    'year': 1999,
    'tourism_receipts': 1243000000,
    'tourism_arrivals': None,
    'tourism_exports': 5.91025,
    'tourism_departures': '',
    'tourism_expenditures': 5.33573,
    'gdp': 75578700000,
    'inflation': 3.33688,
    'unemployment': '11.158'},
   {'country': 'China',
    'country_code': 'CHN',
    'year': 1999,
    'tourism_receipts': 15006000000,
    'tourism_arrivals': 72796000,
    'tourism_exports': 10.0117,
    'tourism_departures': '9232000.0',
    'tourism_expenditures': 9.74565,
    'gdp': 1094000000000,
    'inflation': -1.40147,
    'unemployment': '3.1'},
   {'country': "Cote d'Ivoire",
    'country_code': 'CIV',
    'year': 1999,
    'tourism_receipts': 107000000,
    'tourism_arrivals': None,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 18871000000,
    'inflation': 0.702376,
    'unemployment': ''},
   {'country': 'Cameroon',
    'country_code': 'CMR',
    'year': 1999,
    'tourism_receipts': 92000000,
    'tourism_arrivals': None,
    'tourism_exports': 4.22295,
    'tourism_departures': '',
    'tourism_expenditures': 9.37073,
    'gdp': 11565800000,
    'inflation': 1.87174,
    'unemployment': ''},
   {'country': 'Congo, Dem. Rep.',
    'country_code': 'COD',
    'year': 1999,
    'tourism_receipts': None,
    'tourism_arrivals': 80000,
    'tourism_exports': None,
    'tourism_departures': '50000.0',
    'tourism_expenditures': None,
    'gdp': 4711260000,
    'inflation': 284.895,
    'unemployment': ''},
   {'country': 'Congo, Rep.',
    'country_code': 'COG',
    'year': 1999,
    'tourism_receipts': 13500000,
    'tourism_arrivals': None,
    'tourism_exports': 0.79098,
    'tourism_departures': '',
    'tourism_expenditures': 5.10145,
    'gdp': 2354770000,
    'inflation': 4.14267,
    'unemployment': ''},
   {'country': 'Colombia',
    'country_code': 'COL',
    'year': 1999,
    'tourism_receipts': 1231000000,
    'tourism_arrivals': 725000,
    'tourism_exports': 8.83045,
    'tourism_departures': '1098000.0',
    'tourism_expenditures': 10.0158,
    'gdp': 86278900000,
    'inflation': 10.8737,
    'unemployment': '20.06'},
   {'country': 'Comoros',
    'country_code': 'COM',
    'year': 1999,
    'tourism_receipts': 19000000,
    'tourism_arrivals': 24000,
    'tourism_exports': None,
    'tourism_departures': '',
    'tourism_expenditures': None,
    'gdp': 382455000,
    'inflation': None,
    'unemployment': ''},
   {'country': 'Cabo Verde',
    'country_code': 'CPV',
    'year': 1999,
    'tourism_receipts': 56000000,
    'tourism_arrivals': 67000,
    'tourism_exports': 45.1171,
    'tourism_departures': '',
    'tourism_expenditures': 13.4425,
    'gdp': 592417000,
    'inflation': 4.35643,
    'unemployment': ''},
   {'country': 'Costa Rica',
    'country_code': 'CRI',
    'year': 1999,
    'tourism_receipts': 1256000000,
    'tourism_arrivals': 1267000,
    'tourism_exports': 20.1955,
    'tourism_departures': '353000.0',
    'tourism_expenditures': 9.84907,
    'gdp': 14254900000,
    'inflation': 10.0453,
    'unemployment': ''},
   {'country': 'Caribbean small states',
    'country_code': 'CSS',
    'year': 1999,
    'tourism_receipts': 5220380000,
    'tourism_arrivals': 9901110,
    'tourism_exports': 57.8885,
    'tourism_departures': '',
    'tourism_expenditures': 10.9741,
    'gdp': 16585400000,
    'inflation': 1.56006,
    'unemployment': ''}],
  'from': 1,
  'to': 50,
  'per_page': 50,
  'total': 6650}}

In [31]:
# below we have converted 'economy' data into the pandas data frame
pd.DataFrame(economy['result']['data'])     # results --> data (inside)

,country,country_code,year,tourism_receipts,tourism_arrivals,tourism_exports,tourism_departures,tourism_expenditures,gdp,inflation,unemployment
0,Aruba,ABW,1999,7.820000e+08,972000.0,62.542900,,9.49539,1.722910e+09,2.280370,
1,Africa Eastern and Southern,AFE,1999,8.034210e+09,15309400.0,12.204000,,7.76054,2.654290e+11,7.819860,
2,Afghanistan,AFG,1999,NaN,NaN,NaN,,NaN,NaN,NaN,
3,Africa Western and Central,AFW,1999,1.443610e+09,3897980.0,3.974480,,6.14729,1.394680e+11,0.372266,
4,Angola,AGO,1999,3.100000e+07,45000.0,0.583858,,2.48964,6.152920e+09,248.196000,
5,Albania,ALB,1999,2.180000e+08,371000.0,55.969200,,3.69901,3.212120e+09,0.389438,18.4
6,Andorra,AND,1999,NaN,9422000.0,NaN,,NaN,1.240300e+09,NaN,
7,Arab World,ARB,1999,NaN,NaN,NaN,,NaN,6.654150e+11,2.669370,
8,United Arab Emirates,ARE,1999,8.930000e+08,NaN,NaN,,NaN,8.444550e+10,NaN,
9,Argentina,ARG,1999,3.175000e+09,2898000.0,11.340400,,15.88910,2.835230e+11,NaN,14.05
10,Armenia,ARM,1999,4.700000e+07,41000.0,12.182400,,5.64557,1.845480e+09,0.648246,11.2
11,American Samoa,ASM,1999,NaN,41000.0,NaN,,NaN,NaN,NaN,
12,Antigua and Barbuda,ATG,1999,NaN,560000.0,NaN,,NaN,8.355150e+08,1.121290,
13,Australia,AUS,1999,1.140800e+10,4459000.0,15.247200,3210000.0,10.36250,3.896520e+11,1.483130,6.876
14,Austria,AUT,1999,1.235800e+10,17467000.0,NaN,,NaN,2.164220e+11,0.568994,4.699
15,Azerbaijan,AZE,1999,9.300000e+07,602000.0,7.254170,1204000.0,7.76645,4.581250e+09,-8.525170,16.25
16,Burundi,BDI,1999,1.200000e+06,26000.0,2.019360,27000.0,NaN,8.080770e+08,3.385420,14.0
17,Belgium,BEL,1999,NaN,6369000.0,NaN,6410000.0,NaN,2.582460e+11,1.120850,8.649
18,Benin,BEN,1999,9.440000e+07,941000.0,15.772100,,7.40482,3.677390e+09,0.326723,
19,Burkina Faso,BFA,1999,NaN,117000.0,NaN,,NaN,3.389570e+09,-1.072610,
20,Bangladesh,BGD,1999,NaN,173000.0,NaN,1103000.0,4.19828,5.127060e+10,6.106700,
21,Bulgaria,BGR,1999,1.184000e+09,5056000.0,20.432200,2376000.0,11.38460,1.362730e+10,2.573040,14.1
22,Bahrain,BHR,1999,7.850000e+08,3280000.0,15.033400,,9.47528,7.528470e+09,-1.287590,
23,"Bahamas, The",BHS,1999,1.598000e+09,3648000.0,72.392900,,11.87380,7.683870e+09,1.254250,7.45
24,Bosnia and Herzegovina,BIH,1999,2.580000e+08,147000.0,19.915600,,2.28851,4.686260e+09,NaN,
25,Belarus,BLR,1999,9.200000e+07,NaN,1.437570,,1.99844,1.213820e+10,293.679000,2.1
26,Belize,BLZ,1999,NaN,340000.0,NaN,,8.29579,1.000250e+09,2.621400,12.84
27,Bermuda,BMU,1999,NaN,549000.0,NaN,,NaN,3.324430e+09,NaN,
28,Bolivia,BOL,1999,1.240000e+08,342000.0,9.461320,253000.0,5.88324,8.285060e+09,2.159520,3.93
29,Brazil,BRA,1999,1.718000e+09,5107000.0,3.152580,2863000.0,5.50654,5.996420e+11,4.858450,11.125
30,Barbados,BRB,1999,7.340000e+08,947000.0,58.108000,,9.75939,2.951820e+09,1.560060,10.61
31,Brunei Darussalam,BRN,1999,NaN,967000.0,NaN,,NaN,6.309070e+09,-0.415628,
32,Bhutan,BTN,1999,9.000000e+06,7200.0,NaN,,NaN,3.993110e+08,6.776990,1.4
33,Botswana,BWA,1999,2.390000e+08,1039000.0,7.995000,,6.48125,5.484260e+09,7.749300,
34,Central African Republic,CAF,1999,8.000000e+06,10000.0,NaN,,NaN,9.994780e+08,-1.414200,
35,Canada,CAN,1999,1.202400e+10,49055000.0,4.245030,,5.40185,6.784120e+11,1.734840,7.583
36,Central Europe and the Baltics,CEB,1999,2.028260e+10,200063000.0,14.132900,103358915.15008,6.42737,4.359310e+11,4.019140,10.4170865946518
37,Switzerland,CHE,1999,9.135000e+09,7154000.0,7.515140,,7.22500,2.978740e+11,0.806444,3.053
38,Channel Islands,CHI,1999,NaN,NaN,NaN,,NaN,6.262740e+09,NaN,
39,Chile,CHL,1999,1.243000e+09,NaN,5.910250,,5.33573,7.557870e+10,3.336880,11.158
40,China,CHN,1999,1.500600e+10,72796000.0,10.011700,9232000.0,9.74565,1.094000e+12,-1.401470,3.1
41,Cote d'Ivoire,CIV,1999,1.070000e+08,NaN,NaN,,NaN,1.887100e+10,0.702376,
42,Cameroon,CMR,1999,9.200000e+07,NaN,4.222950,,9.37073,1.156580e+10,1.871740,
43,"Congo, Dem. Rep.",COD,1999,NaN,80000.0,NaN,50000.0,NaN,4.711260e+09,284.895000,
44,"Congo, Rep.",COG,1999,1.350000e+07,NaN,0.790980,,5.10145,2.354770e+09,4.142670,
45,Colombia,COL,1999,1.231000e+09,725000.0,8.830450,1098000.0,10.01580,8.627890e+10,10.873700,20.06
46,Comoros,COM,1999,1.900000e+07,24000.0,NaN,,NaN,3.824550e+08,NaN,
47,Cabo Verde,CPV,1999,5.600000e+07,67000.0,45.117100,,13.44250,5.924170e+08,4.356430,
48,Costa Rica,CRI,1999,1.256000e+09,1267000.0,20.195500,353000.0,9.84907,1.425490e+10,10.045300,
49,Caribbean small states,CSS,1999,5.220380e+09,9901110.0,57.888500,,10.97410,1.658540e+10,1.560060,

In [32]:
# importing only the required data and storing it in a object and making a csv file of it and uploading it on 'kaggle'

my_data = pd.DataFrame(economy['result']['data'], columns=['country', 'year', 'gdp', 'inflation', 'unemployment'])
my_data.to_csv('country and their economic dynaics.csv', index = False)

In [52]:
data = pd.DataFrame(economy['result']['data'])
data.iloc[:, [0,2,4,7,8,9,10]]

,country,year,tourism_arrivals,tourism_expenditures,gdp,inflation,unemployment
0,Aruba,1999,972000.0,9.49539,1.722910e+09,2.280370,
1,Africa Eastern and Southern,1999,15309400.0,7.76054,2.654290e+11,7.819860,
2,Afghanistan,1999,NaN,NaN,NaN,NaN,
3,Africa Western and Central,1999,3897980.0,6.14729,1.394680e+11,0.372266,
4,Angola,1999,45000.0,2.48964,6.152920e+09,248.196000,
5,Albania,1999,371000.0,3.69901,3.212120e+09,0.389438,18.4
6,Andorra,1999,9422000.0,NaN,1.240300e+09,NaN,
7,Arab World,1999,NaN,NaN,6.654150e+11,2.669370,
8,United Arab Emirates,1999,NaN,NaN,8.444550e+10,NaN,
9,Argentina,1999,2898000.0,15.88910,2.835230e+11,NaN,14.05
10,Armenia,1999,41000.0,5.64557,1.845480e+09,0.648246,11.2
11,American Samoa,1999,41000.0,NaN,NaN,NaN,
12,Antigua and Barbuda,1999,560000.0,NaN,8.355150e+08,1.121290,
13,Australia,1999,4459000.0,10.36250,3.896520e+11,1.483130,6.876
14,Austria,1999,17467000.0,NaN,2.164220e+11,0.568994,4.699
15,Azerbaijan,1999,602000.0,7.76645,4.581250e+09,-8.525170,16.25
16,Burundi,1999,26000.0,NaN,8.080770e+08,3.385420,14.0
17,Belgium,1999,6369000.0,NaN,2.582460e+11,1.120850,8.649
18,Benin,1999,941000.0,7.40482,3.677390e+09,0.326723,
19,Burkina Faso,1999,117000.0,NaN,3.389570e+09,-1.072610,
20,Bangladesh,1999,173000.0,4.19828,5.127060e+10,6.106700,
21,Bulgaria,1999,5056000.0,11.38460,1.362730e+10,2.573040,14.1
22,Bahrain,1999,3280000.0,9.47528,7.528470e+09,-1.287590,
23,"Bahamas, The",1999,3648000.0,11.87380,7.683870e+09,1.254250,7.45
24,Bosnia and Herzegovina,1999,147000.0,2.28851,4.686260e+09,NaN,
25,Belarus,1999,NaN,1.99844,1.213820e+10,293.679000,2.1
26,Belize,1999,340000.0,8.29579,1.000250e+09,2.621400,12.84
27,Bermuda,1999,549000.0,NaN,3.324430e+09,NaN,
28,Bolivia,1999,342000.0,5.88324,8.285060e+09,2.159520,3.93
29,Brazil,1999,5107000.0,5.50654,5.996420e+11,4.858450,11.125
30,Barbados,1999,947000.0,9.75939,2.951820e+09,1.560060,10.61
31,Brunei Darussalam,1999,967000.0,NaN,6.309070e+09,-0.415628,
32,Bhutan,1999,7200.0,NaN,3.993110e+08,6.776990,1.4
33,Botswana,1999,1039000.0,6.48125,5.484260e+09,7.749300,
34,Central African Republic,1999,10000.0,NaN,9.994780e+08,-1.414200,
35,Canada,1999,49055000.0,5.40185,6.784120e+11,1.734840,7.583
36,Central Europe and the Baltics,1999,200063000.0,6.42737,4.359310e+11,4.019140,10.4170865946518
37,Switzerland,1999,7154000.0,7.22500,2.978740e+11,0.806444,3.053
38,Channel Islands,1999,NaN,NaN,6.262740e+09,NaN,
39,Chile,1999,NaN,5.33573,7.557870e+10,3.336880,11.158
40,China,1999,72796000.0,9.74565,1.094000e+12,-1.401470,3.1
41,Cote d'Ivoire,1999,NaN,NaN,1.887100e+10,0.702376,
42,Cameroon,1999,NaN,9.37073,1.156580e+10,1.871740,
43,"Congo, Dem. Rep.",1999,80000.0,NaN,4.711260e+09,284.895000,
44,"Congo, Rep.",1999,NaN,5.10145,2.354770e+09,4.142670,
45,Colombia,1999,725000.0,10.01580,8.627890e+10,10.873700,20.06
46,Comoros,1999,24000.0,NaN,3.824550e+08,NaN,
47,Cabo Verde,1999,67000.0,13.44250,5.924170e+08,4.356430,
48,Costa Rica,1999,1267000.0,9.84907,1.425490e+10,10.045300,
49,Caribbean small states,1999,9901110.0,10.97410,1.658540e+10,1.560060,